# Generated by Django 4.1.1 on 2022-10-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nome', models.CharField(max_length=50)),
                ('prod_description_short', models.CharField(max_length=100)),
                ('prod_description_long', models.CharField(max_length=1000)),
                ('prod_image', models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m')),
                ('prod_slug', models.SlugField(unique=True)),
                ('prod_price', models.FloatField()),
                ('prod_price_sale', models.FloatField(default=0)),
                ('prod_type', models.CharField(choices=[('V', 'Variable'), ('S', 'Simple')], default='V', max_length=1)),
            ],
        ),
    ]
