# Generated by Django 4.1.1 on 2022-10-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_nome',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_description_long',
            field=models.CharField(max_length=1000, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_description_short',
            field=models.CharField(max_length=100, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price_sale',
            field=models.FloatField(default=0, verbose_name='Sale price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.CharField(choices=[('V', 'Variable'), ('S', 'Simple')], default='V', max_length=1, verbose_name='Product type'),
        ),
    ]
