# Generated by Django 4.1.1 on 2022-10-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_prod_nome_product_prod_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('variety_price', models.FloatField(verbose_name='Price')),
                ('variety_price_sale', models.FloatField(default=0, verbose_name='Sale price')),
                ('variety_inventory', models.PositiveIntegerField(default=0, verbose_name='Inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
        ),
    ]
