# Generated by Django 4.1.1 on 2022-10-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_variety'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name': 'Variety', 'verbose_name_plural': 'Varieties'},
        ),
    ]
