# Generated by Django 4.1.1 on 2022-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_variety_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
